export const HOTEL_ACTIONS = {
  SET_LOADING: 'FLIGHT/SET_LOADING',
  SET_LIST: 'FLIGHT/SET_LIST',
};

export const GLOBAL_ACTIONS = {
  SEARCH_DISPATCH_SEARCH_QUERY: 'SEARCH/DISPATCH_SEARCH_QUERY',
};
